name: dart_extensionz
description: A set of Dart extensions I use in various projects. Including Boolean, DateTime extensions and more.
version: 7.1.6
repository: https://github.com/mj12358/dart-extensionz
funding:
  - https://www.buymeacoffee.com/mj12358
topics:
  - dart
  - extension

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2

dev_dependencies:
  # dart run coverage:test_with_coverage
  coverage: 1.13.1
  dart_lintz: 1.2.3
  file: 7.0.1
  path: 1.9.1
  test: 1.26.2
